import Head from 'next/head'
import { getSession, useSession, signOut } from 'next-auth/react'
import Button from '@/components/Button'
import Link from 'next/link'


export default function Home() {
    const { data: session } = useSession()

    function handleSignOut() {
        signOut()
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {session ? User({session, handleSignOut}) : Guest()}
        </>
    )
}

function Guest() {
    return (
        <div>
            <h3>Guest Homepage</h3>
            <Link href="/"><a>Log in</a></Link>
        </div>
    )
}

function User({ session, handleSignOut }:any) {
    return (
        <div>
            <p>{session.user.email}</p>
            <Button onClick={handleSignOut}>Sign out</Button>
        </div>
    )
}

export async function getServerSideProps({ req }: any) {
    const session = await getSession({ req })

    if (!session) {
        return {
            redirect: {
                destination: '/auth/login',
                permanent: false
            }
        }
    }

    return {
        props: { session }
    }
}